### PR TITLE
[MRG] fix hyper-params being numpy arrays when using json serialization

### PR DESCRIPTION
**Pull request by kushalkolar**
Fix for #300

### CODE REVIEW

**Comment by rtavenar** [comment]
Hi @kushalkolar 

Thanks for this. Is this fix ready for a review?

**Comment by kushalkolar** [comment]
Hi, this is almost done I think. I'll have time to do a final check this weekend.

**Comment by kushalkolar** [comment]
there are a few issues, working on them...

**Comment by kushalkolar** [comment]
Strange problem, `str` values in the json dict are being loaded as `byte` instead of `str` . Only occurs on Azure pipelines for `Python > 3.5` . All tests pass on my machine with Python v 3.6.9 in a new environment.

https://dev.azure.com/romaintavenard/tslearn/_build/results?buildId=613&view=logs&j=2be6c4c4-5686-59af-cf68-3a679e2e3621&t=2351605f-6b02-5ff5-6355-77123b6aa60f&l=689

There doesn't seem to be any kwarg to force json to loadstrings as `str` instead of `byte`, but I've never encountered this strange issue before. https://docs.python.org/3/library/json.html#json.load

**Comment by rtavenar** [comment]
This bug is fixed in the subfolders branch. You can either set this branch as the target branch for this PR or have a look at it to see how I fixed it there.

Then maybe I could start a review when tests pass.

**Comment by kushalkolar** [comment]
Set the target as the subfolders branch,  ``TimeSeriesSVM`` is failing on python3.6, do you have an idea? https://dev.azure.com/romaintavenard/tslearn/_build/results?buildId=614&view=logs&j=2e703997-b85c-5955-fe15-cdf93bef6757&t=b1b94f87-1d38-5554-e373-8f4cd3c9d658&l=359

**Comment by rtavenar** [comment]
> Set the target as the subfolders branch, `TimeSeriesSVM` is failing on python3.6, do you have an idea? https://dev.azure.com/romaintavenard/tslearn/_build/results?buildId=614&view=logs&j=2e703997-b85c-5955-fe15-cdf93bef6757&t=b1b94f87-1d38-5554-e373-8f4cd3c9d658&l=359

Yeah, it sometimes does but it's nothing important (yet we should find a workaround to not get bothered by these anymore), I just re-ran the failed job and it is likely to succeed I think.

Can I merge to subfolders then?

**Comment by kushalkolar** [comment]
Yup, it's good to go!

**Comment by rtavenar** [comment]
Great! I'll just wait for tests to pass and merge.

Fixes #300 
Fixes #304

**Pull request merged**
