### PR TITLE
[MRG] Adapt to scikit-learn 1.0 + fix deprecated dtypes

### PR DESCRIPTION
**Pull request by YannCabanes**
This PR is related to both PR 379 (adapt scikit-learn 1.0) and to PR 400 (fix deprecated dtypes).

### CODE REVIEW

**Comment by GillesVandewiele** [comment]
This is probably also related to #379? We are currently having some issues with our CI & CD with regards to some obscure numpy errors. We hope to have this fixed in the nearby future.

**Comment by GillesVandewiele** [comment]
We could remove Python 3.6 from our CI/CD btw, end of life was reached 5 months ago (https://endoflife.date/python)

**Comment by YannCabanes** [comment]
Yes, this PR is related to both #379 (adapt to scikit-learn 1.0) and to #400  (fix deprecated dtypes).
Ok, I will try to remove Python 3.6 from the Continuous Intergration by modifying the azure-pipelines.yml file.

**Comment by rtavenar** [comment]
Oh, so now everything passes tests? Great!

Last thing to check is the docs, I will have to dig that next week...

**Comment by rtavenar** [comment]
@YannCabanes this seems to work!

Do you have something else in mind or should we merge soon?

**Comment by YannCabanes** [comment]
This is fine for me, we can merge. Can I let you do it?

**Comment by YannCabanes** [comment]
Once it is merged, I think that we can close both PR #379 (adapt to scikit-learn 1.0) and PR #400 (fix deprecated dtypes) as I have copy pasted all their modifications in the present PR.

**Comment by rtavenar** [comment]
Hum, copy-pasting is not good practice. Could you at least edit your commits to add the required authors as commit co-authors?

These pages should help:
- https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors
- https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

**Comment by rtavenar** [comment]
Maybe the last option is OK since we squash and merge (and hence the PR is merged as a single commit).

**Comment by YannCabanes** [comment]
Ok, perfect!
I still need the email address associated with the GitHub account of @nilesh05apr, then I will do this last commit adding GillesVandewiele and nilesh05apr as co-authors before merging.

**Comment by rtavenar** [comment]
Have a look there to find it: https://github.com/dwyl/dev-setup/issues/22#issuecomment-1098948708

**Comment by nilesh05apr** [comment]
@YannCabanes my email associated with github is nk8588338@gmail.com

**Comment by rtavenar** [comment]
Please check your slack messages :)

I think you have an issue in the way you declare commit co-authors.

**Comment by GillesVandewiele** [comment]
If the co-author crediting is fixed, then this is fine to merge for me (I don't mind being credited or not, but do agree that other new contributors should be credited for their work). In advance already a big thank you, this is really huge for the repo as we have been struggling with failing CI/CDs for far too long.

**Comment by rtavenar** [comment]
This is now merged to `main` branch. Congrats @nilesh05apr and @YannCabanes on your first official `tslearn` contribution!

**Pull request merged**
