### PR TITLE
Remove support for Python 3.7

### PR DESCRIPTION
**Pull request by YannCabanes**
Python version 3.7 end of life's date is 2023-06-27:
https://devguide.python.org/versions/#supported-versions

### CODE REVIEW

**Comment by johannfaouzi** [comment]
Hi,

I've been looking around on the Internet and it seems like this is a system-level issue (Python being installed without the bz2 package). I was not able to reproduce it locally on my MacBook. I guess that it's more of an issue from Azure-Pipelines (i.e., which build of Python 3.7 for Mac is used).

I would also like to mention that [Python 3.7 will no longer be supported starting June 27, 2023](https://devguide.python.org/versions/#supported-versions) (that is, in two days). You can already see that the installed versions of the dependencies are older for the Python 3.7 job that for the other jobs. Moreover, Python 3.11 has been released October 02, 2022 (so almost 9 months ago). I would suggest dropping support for Python 3.7 and adding support 3.11.

So I would suggest to ignore the CI issue and to update the supported Python versions (which will automatically address the CI issue)!

**Comment by YannCabanes** [comment]
An error occur for MacOS with Python37:

```
=================================== FAILURES ===================================
_______________ [doctest] tslearn.utils.cast.from_pyflux_dataset _______________
454 
455     Returns
456     -------
457     array, shape=(n_ts, sz, d), where n_ts=1
458         tslearn-formatted dataset.
459         Column order is kept the same as in the original data frame.
460 
461     Examples
462     --------
463     >>> import pandas as pd
UNEXPECTED EXCEPTION: ModuleNotFoundError("No module named '_bz2'")
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/doctest.py", line 1337, in __run
    compileflags, 1), test.globs)
  File "<doctest tslearn.utils.cast.from_pyflux_dataset[0]>", line 1, in <module>
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pandas/core/generic.py", line 122, in <module>
    from pandas.core.describe import describe_ndframe
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pandas/core/describe.py", line 39, in <module>
    from pandas.io.formats.format import format_percentiles
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pandas/io/formats/format.py", line 99, in <module>
    from pandas.io.common import stringify_path
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pandas/io/common.py", line 4, in <module>
    import bz2
  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

...

=========================== short test summary info ============================
FAILED tslearn/utils/cast.py::tslearn.utils.cast.from_pyflux_dataset
FAILED tslearn/utils/cast.py::tslearn.utils.cast.from_sktime_dataset
FAILED tslearn/utils/cast.py::tslearn.utils.cast.from_tsfresh_dataset
FAILED tslearn/utils/cast.py::tslearn.utils.cast.to_pyflux_dataset
FAILED tslearn/utils/cast.py::tslearn.utils.cast.to_sktime_dataset
FAILED tslearn/utils/cast.py::tslearn.utils.cast.to_tsfresh_dataset
= 6 failed, 154 passed, 2 skipped, 21 deselected, 128 warnings in 569.43s (0:09:29) =
##[error]Bash exited with code '1'.
Async Command Start: Publish test results
Publishing test results to test run '18128'.
TestResults To Publish 162, Test run id:18128
Test results publishing 162, remaining: 0. Test run id: 18128
Published Test Run : https://dev.azure.com/romaintavenard/tslearn/_TestManagement/Runs?runId=18128&_a=runCharts
Flaky failed test results are opted out of pass percentage
Async Command End: Publish test results
Finishing: Test
```

**Comment by YannCabanes** [comment]
Tests are failing for Python 3.11 when used with tensorflow 2.9.0:

```
      Successfully uninstalled scikit-learn-1.2.2
Successfully installed scikit-learn-1.0
+ python -m pip install tensorflow==2.9.0
ERROR: Could not find a version that satisfies the requirement tensorflow==2.9.0 (from versions: 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2)
ERROR: No matching distribution found for tensorflow==2.9.0

```

**Comment by johannfaouzi** [comment]
There seem to be specific versions of some packages that are installed in the CI:
```
python -m pip install scikit-learn==1.0
python -m pip install tensorflow==2.9.0
```

Is there any reason to do this? The tests are only run with (not so) old versions of these packages.

I see that you changed the version of tensorflow, and now there are new errors (probably related to the newest version of this package) that were not captured by the CI before. A temporary fix would be to set a maximum version for tensorflow in the dependencies. But it's a bit unrelated to your PR on soft-dtw.

**Comment by YannCabanes** [comment]
All tests are failing (except readthedocs) with the following error message due to `LearningShapelets`:

```
=================================== FAILURES ===================================
___________ test_all_estimators[LearningShapelets-LearningShapelets] ___________

name = 'LearningShapelets'
Estimator = <class 'tslearn.shapelets.shapelets.LearningShapelets'>

    @pytest.mark.parametrize('name, Estimator', get_estimators('all'))
    def test_all_estimators(name, Estimator):
        """Test all the estimators in tslearn."""
        allow_nan = (hasattr(checks, 'ALLOW_NAN') and
                     Estimator().get_tags()["allow_nan"])
        if allow_nan:
            checks.ALLOW_NAN.append(name)
        if name in ["GlobalAlignmentKernelKMeans", "ShapeletModel",
                    "SerializableShapeletModel"]:
            # Deprecated models
            return
>       check_estimator(Estimator)

tslearn/tests/test_estimators.py:215: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tslearn/tests/test_estimators.py:197: in check_estimator
    check(estimator)
tslearn/tests/sklearn_patches.py:295: in check_classifiers_classes
    check_classifiers_predictions(X, y_, name, classifier_orig)
/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/sklearn/utils/_testing.py:311: in wrapper
    return fn(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

X = array([[-0.84118762, -1.37894673, -1.88806533, ...,  1.1945725 ,
         1.36157375,  1.97347041],
       [-0.40654  ...259, -0.29293702],
       [ 2.01259303,  1.54825042,  1.19081344, ..., -1.59204839,
        -1.56189296, -1.11334695]])
y = array(['three', 'two', 'one', 'two', 'three', 'one', 'two', 'two', 'one',
       'two', 'two', 'two', 'one', 'three', ...'two', 'three', 'one',
E            x: array(['one', 'three', 'two'], dtype='<U5')
E            y: array(['one', 'two'], dtype='<U3')

/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/sklearn/utils/estimator_checks.py:2614: AssertionError

...

=========================== short test summary info ============================
FAILED tslearn/tests/test_estimators.py::test_all_estimators[LearningShapelets-LearningShapelets]
FAILED tslearn/tests/test_shapelets.py::test_shapelets - RuntimeError: Should...
====== 2 failed, 180 passed, 1 skipped, 264 warnings in 289.24s (0:04:49) ======
##[error]Bash exited with code '1'.

```

**Comment by YannCabanes** [comment]
This error is related to the error message mentioned in the PR #427.

**Comment by johannfaouzi** [comment]
For me it's fine, but I don't know if the supported Python versions are mentioned elsewhere in the repository. If so, this PR should change this everywhere. I checked the `setup.py` file and it's not specified here. It's not mentioned either in the `Installation` page in the documentation. So it might be fine.

We should also check what is urgent for the tutorial and what is not. We can impose some restrictions on the Python versions and the versions of the dependencies that are supported for the tutorial.

**Comment by rtavenar** [comment]
Yep, it's fine for me to remove support for 3.7 and delay support for 3.11 to a later PR.

**Pull request merged**
