### PR TITLE
Added save model functionality for shapelets

### PR DESCRIPTION
**Pull request by gio8tisu**
Added get_config in LocalSquaredDistanceLayer class and a couple wrappers to keras' save/load_model functionalities.

```python
"""Train shapelet model, save, load and predict."""

import pickle
from tslearn import shapelets

# Create mock model.
shp_clf = shapelets.ShapeletModel({10:5}, max_iter=1)
shp_clf.fit(X_train, y_train)

# Save it using custom method.
shp_clf.save('shapelet_model.h5')
# You probably also want to save/pickle the label_binarizer.
with open('label_binarizer.pkl', 'wb') as f:
    pickle.dump(shp_clf.label_binarizer, f)

# Delete trained model and load it from file.
del shp_clf
new_shp_clf = shapelets.load_model('shapelet_model.h5')

# Predict class probabilities.
X = new_data
y_probs = new_shp_clf.predict(X) 

# Load the label_binarizer to get the predicted label.
with open('label_binarizer.pkl', 'rb', f):
    label_binarizer = pickle.load(f)

y_pred =  label_binarizer.inverse_transform(y_probs)  # predicted labels for input data X
```

### CODE REVIEW

**Comment by rtavenar** [comment]
Hi @gio8tisu,

Thanks for contributing to tslearn. This is a very good idea to add save/load functionality to the shapelets model. One remark though: it would be nice if the loaded model was a `ShapeletModel` not a `keras` model so that people don't get confused and they could use `transform()` method and so on.

This might require to save the label binarizer as in your example also.

Could you try that?

Best,
Romain

**Comment by gio8tisu** [comment]
Sure, that would definitely be much better. The way I did it was a quick and dirty way.
Sorry for the late reply, I have been pretty busy. I will try to modify the method for saving the entire ShapeletModel as soon as i have some spare time.

BR,
Sergio

**Comment by murometz** [comment]
Hi @rtavenar 

Is this save code committed to master, so I can install it via pip? install git+https://github.com/rtavenar/tslearn.git

Thanks!

Best regards
Ilja

**Comment by gio8tisu** [comment]
Hi @murometz, the code is not in the master branch because it is not a final version. But you can install it from my fork ( [https://github.com/gio8tisu/tslearn](https://github.com/gio8tisu/tslearn) ) and try to run a simple example like the one above.

**Comment by murometz** [comment]
> Hi @murometz, the code is not in the master branch because it is not a final version. But you can install it from my fork ( https://github.com/gio8tisu/tslearn ) and try to run a simple example like the one above.



> Hi @murometz, the code is not in the master branch because it is not a final version. But you can install it from my fork ( https://github.com/gio8tisu/tslearn ) and try to run a simple example like the one above.

Hi @gio8tisu 

Thank you!

**Comment by murometz** [comment]
Hi @gio8tisu 

There is no such method "save" (neither load) in "ShapeletModel".
I've installed from your fork and looked up in code on GitHub too (https://github.com/gio8tisu/tslearn ).
May be, you have submitted wrong version?
Thank you for your time!
Regards
Ilja

**Comment by GillesVandewiele** [comment]
hey @murometz there are different branches in @gio8tisu his repository, make sure to checkout to the `save_shapelet_model` branch :)

**Comment by murometz** [comment]
Hi @gio8tisu @GillesVandewiele 

I could save and load again the model. This is great.
But the predict throws error.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-199-fa8123d0e422> in <module>()
      1 predicted_labels = new_shp_clf.predict(X_test)
----> 2 print("Correct classification rate:", accuracy_score(y_test, predicted_labels))

/anaconda3/envs/fresh_energy/lib/python3.6/site-packages/sklearn/metrics/classification.py in accuracy_score(y_true, y_pred, normalize, sample_weight)
    174 
    175     # Compute accuracy for each possible representation
--> 176     y_type, y_true, y_pred = _check_targets(y_true, y_pred)
    177     check_consistent_length(y_true, y_pred, sample_weight)
    178     if y_type.startswith('multilabel'):

/anaconda3/envs/fresh_energy/lib/python3.6/site-packages/sklearn/metrics/classification.py in _check_targets(y_true, y_pred)
     79     if len(y_type) > 1:
     80         raise ValueError("Classification metrics can't handle a mix of {0} "
---> 81                          "and {1} targets".format(type_true, type_pred))
     82 
     83     # We can't have more than one value on y_type => The set is no more needed

**ValueError: Classification metrics can't handle a mix of multiclass and continuous-multioutput targets**

Same model can normally predict (no exceptions) without being saved and loaded again.

Any idea how can I fix it?
Thank you very much for your time!
Regards
Ilja

**Comment by rtavenar** [comment]
This functionality is included since merge of #227

**Pull request closed without merging**
