### PR TITLE
changed depricated dtypes

### PR DESCRIPTION
**Pull request by nilesh05apr**
DeprecationWarning: np.float and np.int are deprecated #386

Changed deprecated dtype numpy.float and numpy.int to float and int respectively at all the occurences.

### CODE REVIEW

**Comment by rtavenar** [comment]
Thanks for this contribution, the changes seem OK, I will have to check for the failing tests.

**Comment by GillesVandewiele** [comment]
Hi Romain,

The test seem to fail here:
```
=================================== FAILURES ===================================
_______ [doctest] tslearn.datasets.ucr_uea.UCR_UEA_datasets.load_dataset _______
236         >>> data_loader = UCR_UEA_datasets()
237         >>> X_train, y_train, X_test, y_test = data_loader.load_dataset(
238         ...         "TwoPatterns")
239         >>> X_train.shape
240         (1000, 128, 1)
241         >>> y_train.shape
242         (1000,)
243         >>> X_train, y_train, X_test, y_test = data_loader.load_dataset(
244         ...         "CinCECGTorso")
245         >>> X_train.shape
UNEXPECTED EXCEPTION: AttributeError("'NoneType' object has no attribute 'shape'",)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)
  File "<doctest tslearn.datasets.ucr_uea.UCR_UEA_datasets.load_dataset[5]>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'shape'
/home/vsts/work/1/s/tslearn/datasets/ucr_uea.py:245: UnexpectedException
```

Perhaps the CinCECGTorso has been removed from timeseriesclassification.com?

**Comment by GillesVandewiele** [comment]
Now the errors are rather weird: 
`E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

**Comment by rtavenar** [comment]
> Now the errors are rather weird: `E ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

I've seen that error somewhere else also, it seems due to some major change in `numpy`: [link](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp)

The surprising bit is that it runs on some platforms but not on all of them, even if the package requirements are the same for all platforms...

**Comment by GillesVandewiele** [comment]
I'll try to take a look later this week (assigned myself as reviewer such that I do not forget)

**Comment by rtavenar** [comment]
@YannCabanes has had a look at this kind of errors, he might be able to give a hand on this (seems like upgrading to newer versions of `numpy` and `tensorflow` might do the trick)

**Comment by GillesVandewiele** [comment]
> @YannCabanes has had a look at this kind of errors, he might be able to give a hand on this (seems like upgrading to newer versions of `numpy` and `tensorflow` might do the trick)

Yes this indeed seems to be the case (at least to fix the numpy issues)!

**Comment by rtavenar** [comment]
Integrated in #406 and merged to `main` branch

**Pull request closed without merging**
