### PR TITLE
[MRG] Bugfix in lcss_path_from_metric

### PR DESCRIPTION
**Pull request by hoangph3**
When I use function `lcss_path` and `lcss_path_from_metric` to compare distance between two time series, two results aren't equal. The example below:
```bash
import numpy as np

np.random.seed(1234)
s1 = np.random.rand(10, 3)
s2 = np.random.rand(6, 3)

eps = 0.6
print(lcss_path(s1, s2, eps))  # ([(4, 0), (6, 2), (7, 3), (9, 5)], 0.6666666666666666)
print(lcss_path_from_metric(s1, s2, eps))  # ([(8, 0), (9, 5)], 0.6666666666666666)
```
This is bug from `lcss_path_from_metric` function, because we don't pass variable to function sequentially. We must pass `mask` variable instead of `acc_cost_mat` variable, and vice versa.

### CODE REVIEW

**Comment by GillesVandewiele** [comment]
Hi @hoangph3 

Thank you so much for this contribution. Do you have any idea as to why Python 3.8 and Python 3.9 tests fail? Are you using something that is perhaps deprecated in those Python versions? If so we should fix this for the future.

**Comment by hoangph3** [comment]
Hi @GillesVandewiele 
I don't know why Python 3.8 and Python 3.9 tests fail. But I have ran smoothly my project on localhost (python 3.8). I just update the function, the output result is very well, same as LCSS algorithm, not update the requirements library.

**Comment by rtavenar** [comment]
Thanks for this bugfix @hoangph3 and sorry for the delay.

Could you add a test in `tests/test_metrics.py` that would ensure that on some example the output of `lcss_path` and `lcss_path_from_metric` are consistent?

**Comment by hoangph3** [comment]
I have add some test in `tests/test_metrics.py`:

```python
def test_lcss_path_from_metric():
    for d in np.arange(1, 5):
        rng = np.random.RandomState()
        s1, s2 = rng.randn(10, d), rng.randn(30, d)

        # Use lcss_path as a reference
        path_ref, sim_ref = tslearn.metrics.lcss_path(s1, s2)

        # Test of using a scipy distance function
        path, sim = tslearn.metrics.lcss_path_from_metric(s1, s2,
                                                          metric="sqeuclidean")

        print('d:', d)
        print('lcss:', path_ref, sim_ref)
        print('lcss from metric:', path, sim)

        np.testing.assert_equal(path, path_ref)
        np.testing.assert_equal(sim, sim_ref)

        # Test of defining a custom function
        def sqeuclidean(x, y):
            return np.sum((x-y)**2)

        path, sim = tslearn.metrics.lcss_path_from_metric(s1, s2,
                                                          metric=sqeuclidean)
        np.testing.assert_equal(path, path_ref)
        np.testing.assert_equal(sim, sim_ref)

        # Test of precomputing the distance matrix
        dist_matrix = cdist(s1, s2, metric="sqeuclidean")
        path, sim = tslearn.metrics.lcss_path_from_metric(dist_matrix,
                                                          metric="precomputed")
        np.testing.assert_equal(path, path_ref)
        np.testing.assert_equal(sim, sim_ref)
```

With your `lcss_path_from_metric` function:

```
$ python3 test_metrics.py                                                                                                                                     1 ⨯ 3 ⚙
d: 1
lcss: [(1, 9), (2, 12), (3, 16), (4, 18), (5, 19), (6, 20), (7, 21), (8, 23), (9, 27)] 0.9
lcss from metric: [(1, 9), (2, 12), (3, 16), (4, 18), (5, 19), (6, 20), (7, 21), (8, 23), (9, 27)] 0.9
d: 2
lcss: [(0, 5), (1, 12), (2, 14), (4, 19), (5, 20), (6, 23), (8, 26), (9, 28)] 0.8
lcss from metric: [(7, 0), (8, 26), (9, 28)] 0.8
Traceback (most recent call last):
  File "/home/ph3/Downloads/test_metrics.py", line 452, in <module>
    test_lcss_path_from_metric()
  File "/home/ph3/Downloads/test_metrics.py", line 165, in test_lcss_path_from_metric
    np.testing.assert_equal(path, path_ref)
  File "/home/ph3/.local/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 337, in assert_equal
    assert_equal(len(actual), len(desired), err_msg, verbose)
  File "/home/ph3/.local/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 425, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 3
 DESIRED: 8
```

But with my `lcss_path_from_metric` function, it passes all test case:

```
$ python3 test_metrics.py                                                                                                                                         3 ⚙
d: 1
lcss: [(0, 13), (1, 14), (2, 16), (3, 17), (4, 18), (5, 19), (6, 20), (7, 23), (8, 26), (9, 27)] 1.0
lcss from metric: [(0, 13), (1, 14), (2, 16), (3, 17), (4, 18), (5, 19), (6, 20), (7, 23), (8, 26), (9, 27)] 1.0
d: 2
lcss: [(1, 3), (2, 5), (3, 7), (4, 8), (5, 10), (6, 19), (7, 20), (8, 21), (9, 28)] 0.9
lcss from metric: [(1, 3), (2, 5), (3, 7), (4, 8), (5, 10), (6, 19), (7, 20), (8, 21), (9, 28)] 0.9
d: 3
lcss: [(1, 2), (3, 5), (8, 16), (9, 17)] 0.4
lcss from metric: [(1, 2), (3, 5), (8, 16), (9, 17)] 0.4
d: 4
lcss: [(0, 12), (1, 13), (3, 15), (7, 19)] 0.4
lcss from metric: [(0, 12), (1, 13), (3, 15), (7, 19)] 0.4
```

**Comment by rtavenar** [comment]
Yep, this has been observed in #400 also.

@GillesVandewiele could you wrap up a quick PR with the test fix for `CinCECGTorso` dataset, so that we have a stable reference that passes tests in `main` against which we can compare proposed Pull Requests?

**Comment by GillesVandewiele** [comment]
> Yep, this has been observed in #400 also.
> 
> @GillesVandewiele could you wrap up a quick PR with the test fix for `CinCECGTorso` dataset, so that we have a stable reference that passes tests in `main` against which we can compare proposed Pull Requests?

On it.

**Comment by rtavenar** [comment]
@hoangph3 We have fixed issues in other PRs such that tests here should now pass. Could you add an empty commit to your branch so that tests re-trigger?

**Comment by hoangph3** [comment]
There are 3 failed tests, i have failure in https://dev.azure.com/romaintavenard/ab3bf0a6-483f-4cd8-867c-972a4d17e716/_apis/build/builds/841/logs/77 with `TimeSeriesSVC`, bacause the `assert_array_equal` method.

```
2022-06-09T14:06:38.1422994Z =================================== FAILURES ===================================
2022-06-09T14:06:38.1423929Z _______________ test_all_estimators[TimeSeriesSVC-TimeSeriesSVC] _______________
2022-06-09T14:06:38.1424127Z 
2022-06-09T14:06:38.1424564Z name = 'TimeSeriesSVC', Estimator = <class 'tslearn.svm.svm.TimeSeriesSVC'>
2022-06-09T14:06:38.1424768Z 
2022-06-09T14:06:38.1425200Z     @pytest.mark.parametrize('name, Estimator', get_estimators('all'))
2022-06-09T14:06:38.1425535Z     def test_all_estimators(name, Estimator):
2022-06-09T14:06:38.1425823Z         """Test all the estimators in tslearn."""
2022-06-09T14:06:38.1426249Z         allow_nan = (hasattr(checks, 'ALLOW_NAN') and
2022-06-09T14:06:38.1426544Z                      Estimator().get_tags()["allow_nan"])
2022-06-09T14:06:38.1426794Z         if allow_nan:
2022-06-09T14:06:38.1427025Z             checks.ALLOW_NAN.append(name)
2022-06-09T14:06:38.1427330Z         if name in ["GlobalAlignmentKernelKMeans", "ShapeletModel",
2022-06-09T14:06:38.1427629Z                     "SerializableShapeletModel"]:
2022-06-09T14:06:38.1427878Z             # Deprecated models
2022-06-09T14:06:38.1428080Z             return
2022-06-09T14:06:38.1428306Z >       check_estimator(Estimator)
2022-06-09T14:06:38.1428420Z 
2022-06-09T14:06:38.1428651Z tslearn/tests/test_estimators.py:215: 
2022-06-09T14:06:38.1428966Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2022-06-09T14:06:38.1429294Z tslearn/tests/test_estimators.py:197: in check_estimator
2022-06-09T14:06:38.1429572Z     check(estimator)
2022-06-09T14:06:38.1430120Z /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/sklearn/utils/_testing.py:311: in wrapper
2022-06-09T14:06:38.1430496Z     return fn(*args, **kwargs)
2022-06-09T14:06:38.1430774Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2022-06-09T14:06:38.1430917Z 
2022-06-09T14:06:38.1431244Z name = 'TimeSeriesSVC'
2022-06-09T14:06:38.1431527Z estimator_orig = TimeSeriesSVC(max_iter=10, probability=True)
2022-06-09T14:06:38.1431688Z 
2022-06-09T14:06:38.1431915Z     @ignore_warnings(category=FutureWarning)
2022-06-09T14:06:38.1432223Z     def check_decision_proba_consistency(name, estimator_orig):
2022-06-09T14:06:38.1432566Z         # Check whether an estimator having both decision_function and
2022-06-09T14:06:38.1432905Z         # predict_proba methods has outputs with perfect rank correlation.
2022-06-09T14:06:38.1433412Z     
2022-06-09T14:06:38.1433613Z         centers = [(2, 2), (4, 4)]
2022-06-09T14:06:38.1433843Z         X, y = make_blobs(
2022-06-09T14:06:38.1434057Z             n_samples=100,
2022-06-09T14:06:38.1434278Z             random_state=0,
2022-06-09T14:06:38.1434488Z             n_features=4,
2022-06-09T14:06:38.1434700Z             centers=centers,
2022-06-09T14:06:38.1434923Z             cluster_std=1.0,
2022-06-09T14:06:38.1435133Z             shuffle=True,
2022-06-09T14:06:38.1435332Z         )
2022-06-09T14:06:38.1435577Z         X_train, X_test, y_train, y_test = train_test_split(
2022-06-09T14:06:38.1435966Z             X, y, test_size=0.2, random_state=0
2022-06-09T14:06:38.1436185Z         )
2022-06-09T14:06:38.1436397Z         estimator = clone(estimator_orig)
2022-06-09T14:06:38.1436615Z     
2022-06-09T14:06:38.1436894Z         if hasattr(estimator, "decision_function") and hasattr(estimator, "predict_proba"):
2022-06-09T14:06:38.1437184Z     
2022-06-09T14:06:38.1437399Z             estimator.fit(X_train, y_train)
2022-06-09T14:06:38.1437721Z             # Since the link function from decision_function() to predict_proba()
2022-06-09T14:06:38.1438073Z             # is sometimes not precise enough (typically expit), we round to the
2022-06-09T14:06:38.1438425Z             # 10th decimal to avoid numerical issues: we compare the rank
2022-06-09T14:06:38.1438764Z             # with deterministic ties rather than get platform specific rank
2022-06-09T14:06:38.1439448Z             # inversions in case of machine level differences.
2022-06-09T14:06:38.1439811Z             a = estimator.predict_proba(X_test)[:, 1].round(decimals=10)
2022-06-09T14:06:38.1440187Z             b = estimator.decision_function(X_test).round(decimals=10)
2022-06-09T14:06:38.1440504Z >           assert_array_equal(rankdata(a), rankdata(b))
2022-06-09T14:06:38.1440774Z E           AssertionError: 
2022-06-09T14:06:38.1440998Z E           Arrays are not equal
2022-06-09T14:06:38.1441201Z E           
2022-06-09T14:06:38.1441427Z E           Mismatched elements: 2 / 20 (10%)
2022-06-09T14:06:38.1441680Z E           Max absolute difference: 1.
2022-06-09T14:06:38.1441935Z E           Max relative difference: 0.5
2022-06-09T14:06:38.1442236Z E            x: array([ 7.,  2.,  5., 16.,  6., 13., 17., 20.,  3.,  1., 12.,  4.,  8.,
2022-06-09T14:06:38.1442549Z E                  18., 19., 14., 11.,  9., 15., 10.])
2022-06-09T14:06:38.1442855Z E            y: array([ 7.,  3.,  5., 16.,  6., 13., 17., 20.,  2.,  1., 12.,  4.,  8.,
2022-06-09T14:06:38.1443170Z E                  18., 19., 14., 11.,  9., 15., 10.])
```

**Comment by rtavenar** [comment]
Last thing before we merge: could you edit the `CHANGELOG.md` file, add a section before `[v0.5.2]` that you name `[Towards v0.5.3]` and state that you fixed this bug in this function?

**Comment by YannCabanes** [comment]
Hello @hoangph3,
Could you please remove the 3 lines of "print" in the file: "tslearn/tests/test_metrics.py":
print('d:', d)
print('lcss:', path_ref, sim_ref)
print('lcss from metric:', path, sim)
Then your PR will be ready to be merged.

**Comment by hoangph3** [comment]
> Thanks a lot and congratulations for your contribution @hoangph3!

Thank sir, it's pleasure to be a part of the project :D

**Pull request merged**
