### PR TITLE
Avoid DivisionByZero in MinMaxScaler

### PR DESCRIPTION
**Pull request by GillesVandewiele**
This PR deals with issue #314. As a fix, I propose to set range_t to 1 where it is 0 so that no division by zero occurs.
```python
range_t[range_t == 0.] = 1.
```

I also added a test for this. We did not have a `test_preprocessing` file yet so I created it. The test is very simple:
```python
def test_single_value_ts_no_nan():
	X = to_time_series_dataset([[1, 1, 1, 1]])

	standard_scaler = TimeSeriesScalerMeanVariance()
	assert np.sum(np.isnan(standard_scaler.fit_transform(X))) == 0

	minmax_scaler = TimeSeriesScalerMinMax()
	assert np.sum(np.isnan(minmax_scaler.fit_transform(X))) == 0
```

### CODE REVIEW

**Comment by GillesVandewiele** [comment]
It seems like I accidently pushed along two very old changes. Only #b491aa2 is relevant. I will try to undo these.

**Comment by rtavenar** [comment]
Hi @GillesVandewiele 

Thanks for the quick fix! WOuld you mind using `subfolders` as base branch so that the changes don't get lost by consecutive merges?

**Comment by GillesVandewiele** [comment]
Yes of course! Let me try that now

**Comment by GillesVandewiele** [comment]
Is this OK @rtavenar? It seems to assign all these changes to this PR now. Want me to close this one and open a new one instead?

**Pull request merged**
