### PR TITLE
Fixing indentation of refs in docs

### PR DESCRIPTION
**Pull request by GillesVandewiele**
This PR handles #238 and fixes the indentation of the references in our docs. 

As the branch structure changed quite a bit, I did not know to which branch I had to merge my PR, tell me if I need to change this :).

### CODE REVIEW

**Comment by rtavenar** [comment]
> As the branch structure changed quite a bit, I did not know to which branch I had to merge my PR, tell me if I need to change this :).

Now it should be simple: merges to master are the correct way to proceed :)

**Comment by rtavenar** [comment]
This looks great! I'll have a look at the resulting built docs before merging though :)

**Comment by GillesVandewiele** [comment]
Yes please do, I actually didn't check it locally... I will take a look as well once it is done building :)

**Comment by GillesVandewiele** [comment]
There's still a few ones mall-formatted. E.g. https://tslearn--239.org.readthedocs.build/en/239/gen_modules/piecewise/tslearn.piecewise.PiecewiseAggregateApproximation.html#tslearn.piecewise.PiecewiseAggregateApproximation

Let me see what's going on there...

**Comment by rtavenar** [comment]
`KShape` is still buggy.
`UCR_UEA_datasets` and `CachedDatasets` too.
`OneD_SAX`, `SAX` and `PAA` too.
`ShapeletModel` and `SerializedShapeletModel` too.

I haven't checked why.

**Comment by GillesVandewiele** [comment]
Is there some documentation available on this citation format? I am currently checking https://build-me-the-docs-please.readthedocs.io/en/latest/Using_Sphinx/UsingBibTeXCitationsInSphinx.html but this looks quite different to our format...

**Comment by rtavenar** [comment]
I couldn't find any good one except this: https://numpydoc.readthedocs.io/en/latest/format.html (where they do not have the indenting I thought was the solution...).

I can try out things locally and let you know.

**Comment by rtavenar** [comment]
OK, so my initial guess was definitely wrong: the bug does not come from indentation. It happens when the same reference is used in several places in the same resulting doc page. I am investigating how things should be done in this case.

**Comment by rtavenar** [comment]
OK so my previous guess was wrong too :)

I think it happens each time we try to have a numbered reference in a class docstring. I don't know why (couldn't find anything related on the web) and I don't know if we should rather remove all numbered references in class docstrings (as done for `GloballignmentKernelKMeans` for example) or just leave it as is with weird reference numbering.

**Comment by GillesVandewiele** [comment]
Perhaps we could change from a number system to this system where the author names are used?

**Comment by rtavenar** [comment]
> Perhaps we could change from a number system to this system where the author names are used?

I tried, but it is ineffective: whatever the key we use, some prefix is added.

**Comment by rtavenar** [comment]
Closing since this was in fact fixed by upgrading numpydoc to 1.0

**Pull request closed without merging**
