### PR TITLE
[MRG] Fix import error when torch is not installed.

### LINKED ISSUE #462: 0.6.0 fails to import when pytorch is not installed with ModuleNotFoundError: No module named 'torch'
## Description

The latest release includes new pytorch backend. Unfortunately, when pytorch is not installed, it fails to fallback to a numpy backend. I managed to reproduce this on two different CI environments (ubuntu linux with python 3.10 and 3.9) and locally (WSL ubuntu with python 3.9).

## How to reproduce
Install latest `tslearn` in a fresh environment:

```shell
➜  python --version
Python 3.9.16
➜  python -m venv .venv
➜  source .venv/bin/activate
(.venv) ➜ pip install tslearn
Collecting tslearn
  Using cached tslearn-0.6.0-py3-none-any.whl (368 kB)
Collecting numpy
  Downloading numpy-1.25.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.7/17.7 MB 9.2 MB/s eta 0:00:00
Collecting numba
  Downloading numba-0.57.1-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 8.8 MB/s eta 0:00:00
Collecting joblib
  Using cached joblib-1.3.1-py3-none-any.whl (301 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.9 MB)
Collecting scipy
  Using cached scipy-1.11.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.5 MB)
Collecting numpy
  Downloading numpy-1.24.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 5.5 MB/s eta 0:00:00
Collecting llvmlite<0.41,>=0.40.0dev0
  Downloading llvmlite-0.40.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.1/42.1 MB 7.5 MB/s eta 0:00:00
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Installing collected packages: threadpoolctl, numpy, llvmlite, joblib, scipy, numba, scikit-learn, tslearn
Successfully installed joblib-1.3.1 llvmlite-0.40.1 numba-0.57.1 numpy-1.24.4 scikit-learn-1.3.0 scipy-1.11.1 threadpoolctl-3.1.0 tslearn-0.6.0
WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.
You should consider upgrading via the '/home/me/tmp/.venv/bin/python -m pip install --upgrade pip' command.
(.venv) ➜  python -c "import tslearn.metrics"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/me/tmp/.venv/lib/python3.9/site-packages/tslearn/metrics/__init__.py", line 8, in <module>
    from .dtw_variants import (dtw, dtw_limited_warping_length,
  File "/home/me/tmp/.venv/lib/python3.9/site-packages/tslearn/metrics/dtw_variants.py", line 6, in <module>
    from tslearn.backend import instantiate_backend
  File "/home/me/tmp/.venv/lib/python3.9/site-packages/tslearn/backend/__init__.py", line 8, in <module>
    from .pytorch_backend import PyTorchBackend
  File "/home/me/tmp/.venv/lib/python3.9/site-packages/tslearn/backend/pytorch_backend.py", line 18, in <module>
    import torch as _torch
ModuleNotFoundError: No module named 'torch'
```

## Expected behavior
I would assume that the importing will fall back to numpy backend when pytorch is not installed via this exception handling https://github.com/tslearn-team/tslearn/blob/main/tslearn/backend/backend.py#L9

I think something is not going as expected while catching the import error exception, but I can't pin point right now what exactly.

# Environments
Local:
 - OS: Ubuntu 20.04
 - python 3.9.16
 - tslearn 0.6.0

CI:
- OS: Ubuntu 22.04.2
- python 3.10.11
- tslearn 0.6.0

### PR DESCRIPTION
**Pull request by eicca**
Init file in `tslearn/backend` imports torch backend, which imports torch. This causes an import error when torch is not installed. This change fixes this issue by removing extra import in `tslearn/backend/__init__.py`

Additionally, this change fixes failing tests when torch is not installed.

Fixes #462

I tried to run the tests locally, but some of them fail with and without pytorch being installed, so I can't say for sure if I fixed all test cases.

When this is fixed, I think some users will appreciate a new release, since the latest version is breaking for everybody who didn't install pytorch. To make things slightly worse, the latest version of pytorch is incompatible with the latest version of tensorflow: https://github.com/pytorch/pytorch/issues/97580, therefore the temporary fix of installing pytorch won't work in some cases.

### CODE REVIEW

**Comment by rtavenar** [comment]
Thanks @eicca for this prompt PR!

@YannCabanes coiuld you have a look?

**Comment by rtavenar** [comment]
Also, if I may add, it could be a good idea to have a test specifically tailored for the no-pytorch context to make sure that we don't make this mistake again in the future, what do you think?

**Comment by eicca** [comment]
Small update: I tried to compare the failing tests with and without pytorch and it looks like the same tests are failing. So I'd assume that this PR does fix all pytorch dependent tests :)

**Comment by rtavenar** [comment]
> Small update: I tried to compare the failing tests with and without pytorch and it looks like the same tests are failing. So I'd assume that this PR does fix all pytorch dependent tests :)

Your edits to `test_metrics.py` should ease the process, I guess what's missing is to have a new test job and make sure it does not have `torch` installed.

**Comment by YannCabanes** [comment]
Thanks a lot for your quick PR @eicca!

**Comment by rtavenar** [comment]
Thanks a lot @eicca ! This is now merged in main, and we will generate a new release from this patch!

**Comment by eicca** [comment]
> Thanks a lot @eicca ! This is now merged in main, and we will generate a new release from this patch!

Thanks a lot @rtavenar and @YannCabanes for taking care of this!

**Pull request merged**
