### PR TITLE
[WIP] Test against python 3.10

### PR DESCRIPTION
**Pull request by petoknm**
Fixes: #374
Now that we have tensorflow 2.8.0 with cp310 support, we can finally test against cp310.

### CODE REVIEW

**Comment by petoknm** [comment]
We might need #375 to be able to find a version of both numpy and sklearn that work in enough environments.

**Comment by GillesVandewiele** [comment]
> We might need #375 to be able to find a version of both numpy and sklearn that work in enough environments.


Thank you so much once again for your contribution! There's a PR ready for that :) #379 , it still needs to get merged.

**Comment by GillesVandewiele** [comment]
@rtavenar can we re-run CI/CD and merge this PR if successful?

**Comment by rtavenar** [comment]
I guess what we need is to merge `main`'s latest version on this branch and see if all tests pass, right?

**Comment by YannCabanes** [comment]
Hello, 
The tests failing are related to the "cesium" package which is not compatible with Python 3.10 yet.
I have done a pull request (PR 305) on the cesium package to make it compatible with Python 3.10:
https://github.com/cesium-ml/cesium/pull/305
This PR has been merged.
Once the next version of the cesium package will be released, tslearn should also be compatible with Python 3.10.
(I have asked to be informed when the next version of the cesium package will be released.)

**Comment by stefanv** [comment]
> Once the next version of the cesium package will be released, tslearn should also be compatible with Python 3.10.

A new release of cesium is out.

**Comment by YannCabanes** [comment]
I have reverted to the previous commit.

**Comment by YannCabanes** [comment]
The support for Python 3.10 has been added in PR #437 in which @petoknm has been added as a co-author.
I now close the current PR #384.

**Pull request closed without merging**
